# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/lenovo/Desktop/debugzju/nightmare/architecture/lab/Computer-Architecture-Lab/Exp6/Exp6.srcs/sources_1/ip/multiple/multiple.xci
# IP: The module: 'multiple' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/lenovo/Desktop/debugzju/nightmare/architecture/lab/Computer-Architecture-Lab/Exp6/Exp6.srcs/sources_1/ip/multiple/multiple_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiple'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Users/lenovo/Desktop/debugzju/nightmare/architecture/lab/Computer-Architecture-Lab/Exp6/Exp6.srcs/sources_1/ip/multiple/multiple.xci
# IP: The module: 'multiple' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/lenovo/Desktop/debugzju/nightmare/architecture/lab/Computer-Architecture-Lab/Exp6/Exp6.srcs/sources_1/ip/multiple/multiple_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiple'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
