# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Users/lenovo/Desktop/debugzju/nightmare/architecture/lab/Computer-Architecture-Lab/Exp6/code/constraint.xdc

# IP: ip/divider/divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider} -quiet] -quiet

# IP: ip/multiple/multiple.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiple || ORIG_REF_NAME==multiple} -quiet] -quiet
